netex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tires/', include('tires.urls')),
]

tires/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'tires'
urlpatterns = [
    url(r'^$', views.TireListView.as_view(), name='list'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.TireDeleteView.as_view(), name='delete'),
    url(r'^create/$', views.TireCreate.as_view(), name='create'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.TireUpdate.as_view(), name='edit')
]

urlpatterns += static(settings.MEDIA_URL, doccument_root=settings.MEDIA_ROOT)

tires/models.py
from django.db import models


class Tire(models.Model):
    width = models.IntegerField()
    height = models.IntegerField()
    diameter = models.IntegerField()
    speed_index = models.IntegerField()
    picture = models.ImageField(upload_to='picturegroup')

    def __str__(self):
        return str(self.pk)

tires/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Tire


class TireListView(generic.ListView):
    template_name = 'tires/tires_list.html'
    context_object_name = 'tires_list'

    def get_queryset(self):
        return Tire.objects.all()


class TireCreate(generic.CreateView):
    model = Tire
    fields = ['width', 'height', 'diameter', 'speed_index', 'picture']
    success_url = reverse_lazy('tires:list')


class TireUpdate(generic.UpdateView):
    model = Tire
    fields = ['width', 'height', 'diameter', 'speed_index', 'picture']
    success_url = reverse_lazy('tires:list')


class TireDeleteView(generic.DeleteView):
    model = Tire
    success_url = reverse_lazy('tires:list')

tires/templates/tires/base.html
<html>
    <head>
        <title>NETEX</title>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

tires/templates/tires/tire_confirm_delete.html
{% extends "tires/base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

tires/templates/tires/tire_form.html
{% extends "tires/base.html" %}

{% block content %}
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

tires/templates/tires/tire_update_form.html
{% extends "tires/base.html" %}

{% block content %}
<form enctype="multipart/form-data" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit" />
</form>
{% endblock %}

tires/templates/tires/tires_list.html
{% extends "tires/base.html" %}

{% block content %}
<a href="{% url 'tires:create'%}">CREATE NEW TIRE</a>
<table>
    <tr>
        <th>width</th>
        <th>height</th>
        <th>diameter</th>
        <th>speed_index</th>
        <th>picture</th>
    </tr>
     {% for tire in tires_list %}
        <tr>
            <td>{{tire.width}}</td>
            <td>{{tire.height}}</td>
            <td>{{tire.diameter}}</td>
            <td>{{tire.speed_index}}</td>
            <td><img src="{{tire.picture.url}}"></td>
            <td><a href="{% url 'tires:edit' tire.pk %}">edit</a></td>
            <td><a href="{% url 'tires:delete' tire.pk %}">delete</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}